from ops import db

class NewCascadeRiskPrjDangerRecord(db.Model):
    __tablename__ = 'new_cascade_risk_prj_danger_record'

    id = db.Column(db.BigInteger, primary_key=True, server_default=db.FetchedValue())
    code = db.Column(db.String(32, 'utf8_bin'), nullable=False, info='隐患编码')
    danger_library_code = db.Column(db.String(32, 'utf8_bin'), info='隐患库编码')
    project_code = db.Column(db.String(255, 'utf8_bin'), info='项目编码')
    project_name = db.Column(db.String(255, 'utf8_bin'), info='项目名称')
    danger_number = db.Column(db.Integer, info='隐患数量')
    major_code = db.Column(db.String(32, 'utf8_bin'), info='专业编码')
    major_name = db.Column(db.String(255, 'utf8_bin'), info='专业名称')
    system_code = db.Column(db.String(32, 'utf8_bin'), info='系统编码')
    major_sort = db.Column(db.String(255, 'utf8_bin'), info='专业排序')
    system_name = db.Column(db.String(20, 'utf8_bin'), info='系统名称')
    system_sort = db.Column(db.String(255, 'utf8_bin'), info='系统排序')
    equipment_code = db.Column(db.String(32, 'utf8_bin'), info='设备编码')
    equipment_name = db.Column(db.String(20, 'utf8_bin'), info='设备名称')
    module_code = db.Column(db.String(32, 'utf8_bin'), info='组件编码')
    module_name = db.Column(db.String(20, 'utf8_bin'), info='组件名称')
    note = db.Column(db.String(255, 'utf8_bin'), info='隐患描述')
    position = db.Column(db.String(255, 'utf8_bin'), info='隐患地点/位置')
    risk_level = db.Column(db.String(1, 'utf8_bin'), info='风险等级 1:低风险 2:中风险 3:高风险')
    area = db.Column(db.String(32, 'utf8_bin'), info='分布区域')
    stage = db.Column(db.String(32, 'utf8_bin'), info='致因阶段 0:设计 1:运营 2:施工 3:装修')
    images_file_id = db.Column(db.String(100, 'utf8_bin'), info='隐患图片文件id,多个逗号隔开')
    write_person = db.Column(db.String(32, 'utf8_bin'), info='录入人')
    write_person_name = db.Column(db.String(32, 'utf8_bin'), info='录入人姓名')
    state = db.Column(db.String(1, 'utf8_bin'), info='状态 1：待整改，2：整改中，3：复查中，4：复查不合格，5：合格已完成')
    frequency = db.Column(db.Integer, info='出现频率')
    voice_time = db.Column(db.Integer, info='录音长度（秒）')
    voice_file_id = db.Column(db.String(100, 'utf8_bin'), info='语音文件id')
    confirm_file_id = db.Column(db.BigInteger, info='手写确认图片')
    confirm_person = db.Column(db.String(32, 'utf8_bin'), info='确认人')
    confirm_person_tel = db.Column(db.String(20, 'utf8_bin'), info='手写确认人电话')
    mark = db.Column(db.String(100, 'utf8_bin'), info='备注')
    upload_time = db.Column(db.DateTime, info='上传时间')
    create_time = db.Column(db.DateTime, info='创建时间')
    create_user = db.Column(db.BigInteger, info='创建人')
    update_time = db.Column(db.DateTime)
    update_user = db.Column(db.BigInteger, info='更新人')
    del_ind = db.Column(db.BIT(1))
    version = db.Column(db.Integer, server_default=db.FetchedValue(), info='乐观锁')
    appflag = db.Column(db.String(32, 'utf8_bin'), info='appflag')
    rule_code = db.Column(db.String(100, 'utf8_bin'), info='法规编号')
    rule_name = db.Column(db.String(1024, 'utf8_bin'), info='法规名称')
    rule_standard = db.Column(db.String(255, 'utf8_bin'), info='法规标准')
    clause = db.Column(db.String(100, 'utf8_bin'), info='相关条款')
    clause_contact = db.Column(db.String(1024, 'utf8_bin'), info='条款内容')
    rectify_advise = db.Column(db.String(1024, 'utf8_bin'), info='整改建议')
    dangerNote = db.Column(db.String(1024, 'utf8_bin'), info='隐患库的隐患描述')
    province = db.Column(db.String(100))
    city = db.Column(db.String(100))
    project_character = db.Column(db.String(255))
    customer_name = db.Column(db.String(255))
    project_tag = db.Column(db.String(255))
    region_tag = db.Column(db.String(255))
    headquarter_tag = db.Column(db.String(255))
    profession_tag = db.Column(db.String(255))
    lng = db.Column(db.Float(10), info='经度')
    lat = db.Column(db.Float(10), info='维度')
    plan_start_time = db.Column(db.DateTime, info='预计开始时间')
    plan_end_time = db.Column(db.DateTime, info='预计结束时间')