from sqlalchemy.dialects.mysql import BIT

from ops import db
class RiskProject(db.Model):
    __tablename__ = 'risk_project'

    id = db.Column(db.BigInteger, primary_key=True)
    code = db.Column(db.String(255, 'utf8_bin'), info='项目编码')
    name = db.Column(db.String(255, 'utf8_bin'), info='项目名称')
    ctr_code = db.Column(db.String(255, 'utf8_bin'), info='合同编码')
    ctr_codes = db.Column(db.String(255, 'utf8_bin'), info='合同父级编码')
    cust_code = db.Column(db.String(32, 'utf8_bin'), info='客户编码')
    feature = db.Column(db.String(255, 'utf8_bin'), info='项目特征')
    status = db.Column(db.String(1, 'utf8_bin'), info='项目状态 0:立项 1:首次会议 2:专业报告 3:末次会议 4:已归档')
    pro_leader_code = db.Column(db.String(32, 'utf8_bin'), info='项目负责人/项目组长')
    pro_leader_name = db.Column(db.String(40, 'utf8_bin'), info='项目组长名字')
    province_code = db.Column(db.String(10, 'utf8_bin'), info='省编码')
    province_name = db.Column(db.String(20, 'utf8_bin'), info='省名称')
    city_code = db.Column(db.String(10, 'utf8_bin'), info='市编码')
    city_name = db.Column(db.String(20, 'utf8_bin'), info='市名')
    district_code = db.Column(db.String(10, 'utf8_bin'), info='区域编码')
    district_name = db.Column(db.String(20, 'utf8_bin'), info='区域名')
    address = db.Column(db.String(100, 'utf8_bin'), info='详细地址')
    full_address = db.Column(db.String(255, 'utf8_bin'), info='完整地址')
    lng = db.Column(db.Float(10), info='经度')
    lat = db.Column(db.Float(10), info='维度')
    leader_phone = db.Column(db.String(32, 'utf8_bin'), info='组长/负责人手机号')
    plan_start_time = db.Column(db.DateTime, info='预计开始时间')
    plan_end_time = db.Column(db.DateTime, info='预计结束时间')
    type = db.Column(db.String(2, 'utf8_bin'), info='检查类型 1:A类检查 2:B类检查  3:C类检查 4:其他类')
    frist_meetting_file_id = db.Column(db.String(255, 'utf8_bin'), info='首次会议文件id')
    professional_report_file_ids = db.Column(db.String(255, 'utf8_bin'))
    end_meeting_file_id = db.Column(db.String(255, 'utf8_bin'), info='末次文件id')
    general_report_file_id = db.Column(db.String(255, 'utf8_bin'), info='综合报告')
    check_unit = db.Column(db.String(32, 'utf8_bin'), info='检查单位')
    amount = db.Column(db.Numeric(18, 2), info='项目金额')
    note = db.Column(db.String(500, 'utf8_bin'), info='项目概况')
    create_time = db.Column(db.DateTime, info='创建时间')
    create_user = db.Column(db.BigInteger, info='创建人')
    update_time = db.Column(db.DateTime)
    update_user = db.Column(db.BigInteger, info='更新人')
    del_ind = db.Column(BIT(1))
    version = db.Column(db.Integer, server_default=db.FetchedValue(), info='乐观锁')
    unit_key = db.Column(db.String(36, 'utf8_bin'), info='唯一标识，用于树形结构')